# Generated by Django 5.0.6 on 2024-07-07 17:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import core.services.file_service


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=20)),
                ('model_type', models.CharField(max_length=20)),
                ('condition_type', models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Unregistered', 'Unregistered'), ('After Accident', 'After Accident')], max_length=20)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)])),
                ('body_type', models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Jeep', 'Jeep')], max_length=9)),
                ('car_photo', models.ImageField(blank=True, upload_to=core.services.file_service.FileService.upload_car_photo)),
                ('advertisement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='advertisements.advertisementmodel')),
            ],
            options={
                'db_table': 'car',
                'ordering': ('-id',),
            },
        ),
    ]
