# Generated by Django 5.0.6 on 2024-07-07 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto_parks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='autoparkmodel',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_parks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autoparkmodel',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_parks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autoparkmodel',
            name='mechanic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mechanic_parks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autoparkmodel',
            name='salesperson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_parks', to=settings.AUTH_USER_MODEL),
        ),
    ]
