# Generated by Django 5.0.6 on 2024-07-07 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=150)),
                ('location', models.CharField(choices=[('VINNYTSIA', 'VINNYTSIA'), ('VOLYN', 'VOLYN'), ('LVIV', 'LVIV'), ('DNIPRO', 'DNIPRO'), ('DONETSK', 'DONETSK'), ('ZHYTOMYR', 'ZHYTOMYR'), ('ZAKARPATTIA', 'ZAKARPATTIA'), ('ZAPORIZHIA', 'ZAPORIZHIA'), ('IVANO_FRANKIVSK', 'IVANO_FRANKIVSK'), ('KYIV', 'KYIV'), ('KIROVOHRAD', 'KIROVOHRAD'), ('LUGANSK', 'LUGANSK'), ('MYKOLAIV', 'MYKOLAIV'), ('ODESA', 'ODESA'), ('POLTAVA', 'POLTAVA'), ('RIVNE', 'RIVNE'), ('SUMY', 'SUMY'), ('TERNOPIL', 'TERNOPIL'), ('KHARKIV', 'KHARKIV'), ('CHERKASY', 'CHERKASY'), ('CHERNIHIV', 'CHERNIHIV'), ('CHERNIVTSI', 'CHERNIVTSI'), ('KHMELNYTSK', 'KHMELNYTSK'), ('SEVASTOPOL', 'SEVASTOPOL'), ('CRIMEA', 'CRIMEA')], max_length=100)),
                ('view_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('UAH', 'UAH')], default='USD', max_length=3)),
            ],
            options={
                'db_table': 'advertisements',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AdvertisementViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('UAH', 'UAH')], max_length=3)),
                ('base_currency', models.CharField(default='UAH', max_length=3)),
                ('buy', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sale', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
